version: '3.4'

services:
  # Identity
  identity_sts:
    image: ${REGISTRY:-microservices-dotnet}/identity_sts:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: src/Services
      dockerfile: Identity/Services.Identity.STS/Development.Dockerfile
    networks:
      - default
    depends_on:
      - sqldata
      - messagebroker

  # API
  ## Localization
  localization_api:
    image: ${REGISTRY:-microservices-dotnet}/localization_api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: src/Services
      dockerfile: Localization/Services.Localization.API/Development.Dockerfile
    networks:
      - default
    depends_on:
      - sqldata
      - redisdata
      - messagebroker
      - identity_sts
  
  # Web
  ## Administration
  #### base-admin
  web_administration_baseadmin:
    image: ${REGISTRY:-microservices-dotnet}/web_administration_baseadmin:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: src/Web/Administration/web-administration
      dockerfile: Development.Dockerfile
    networks:
      - default
    depends_on:
      - identity_sts
  
  # Databases
  ## SQL
  sqldata:
    image: mysql:8
    restart: always
    networks:
      - default
  ## NoSQL
  nosqldata:
    image: mongo:4
    networks:
      - default
  
  # Redis
  redisdata:
    image: redis:5-alpine
    networks:
      - default
  
  # Message Broker
  messagebroker:
    image: rabbitmq:3-management
    networks:
      - default

networks:
  default:
    driver: bridge
