version: '3.4'

services:
    # Identity
    identity_sts:
        volumes:
            - ~/vsdbg:/vsdbg:ro
            - .:/workspace
            # - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
            # - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    # API
    ## Localization
    resources_api:
        volumes:
            - ~/vsdbg:/vsdbg:ro
            - .:/workspace
            # - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
            # - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
