version: '3.4'

services:
    # Identity
    identity_sts:
        image: ${REGISTRY:-microservices-dotnet}/identity_sts:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: Identity/Services.Identity.STS/Development.Dockerfile
            args:
                - HTTP_PORT=${MICROSERVICESDOTNET_IDENTITY_STS_INTERNAL_PORT}
        networks:
            - default
        depends_on:
            - sqldata
            - messagebroker

    # API
    ## Resources
    resources_api:
        image: ${REGISTRY:-microservices-dotnet}/resources_api:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: Resources/Services.Resources.API/Development.Dockerfile
            args:
                - HTTP_PORT=${MICROSERVICESDOTNET_RESOURCES_API_INTERNAL_HTTP_PORT}
        networks:
            - default
        depends_on:
            - sqldata
            - redisdata
            - messagebroker
            - identity_sts

    # Databases
    ## SQL
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        networks:
            - default
    ## NoSQL
    nosqldata:
        image: mongo:4
        networks:
            - default

    # Redis
    redisdata:
        image: redis:5-alpine
        networks:
            - default

    # Message Broker
    messagebroker:
        image: rabbitmq:3-management
        networks:
            - default

networks:
    default:
        driver: bridge
