version: '3.4'

services:
    # Identity
    identity_sts:
        env_file:
            - Identity/Services.Identity.STS/Development.env
        environment:
            Ports__Http: '${MICROSERVICESDOTNET_IDENTITY_STS_INTERNAL_PORT}'
            ConnectionStrings__Sql: 'Server=tcp:sqldata;Initial Catalog=microservicesdotnet.services.identitydb;User Id=sa;Password=${MICROSERVICESDOTNET_SQL_SA_PASSWORD};'
            InternalEndpoints__grpcResources: 'http://resources_api:${MICROSERVICESDOTNET_RESOURCES_API_INTERNAL_GRPC_PORT}'
            ExternalEndpoint: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}'
            ClientEndpoints__resources_api: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_RESOURCES_API_PORT}'
            ClientEndpoints__web_base_administration: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_WEB_BASE_ADMINISTRATION_PORT}'
        ports:
            - '${MICROSERVICESDOTNET_IDENTITY_STS_PORT}:${MICROSERVICESDOTNET_IDENTITY_STS_INTERNAL_PORT}'
        expose:
            - '${MICROSERVICESDOTNET_IDENTITY_STS_PORT}'
        # volumes:
            # - ~/vsdbg:/vsdbg:ro
            # - .:/workspace
            # - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
            # - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    # API
    ## Resources
    resources_api:
        env_file:
            - Resources/Services.Resources.API/Development.env
        environment:
            Ports__Http: '${MICROSERVICESDOTNET_RESOURCES_API_INTERNAL_HTTP_PORT}'
            Ports__Grpc: '${MICROSERVICESDOTNET_RESOURCES_API_INTERNAL_GRPC_PORT}'
            ConnectionStrings__Sql: 'Server=tcp:sqldata;Initial Catalog=microservicesdotnet.services.resourcesdb;User Id=sa;Password=${MICROSERVICESDOTNET_SQL_SA_PASSWORD};'
            ConnectionStrings__Redis: ${MICROSERVICESDOTNET_REDIS_DB:-redisdata}
            IdentityUrl: 'http://identity_sts:${MICROSERVICESDOTNET_IDENTITY_STS_INTERNAL_PORT}'
            IdentityUrlExternal: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}'
        ports:
            - '${MICROSERVICESDOTNET_RESOURCES_API_PORT}:${MICROSERVICESDOTNET_RESOURCES_API_INTERNAL_HTTP_PORT}'
        expose:
            - '${MICROSERVICESDOTNET_RESOURCES_API_PORT}'
        # volumes:
            # - ~/vsdbg:/vsdbg:ro
            # - .:/workspace
            # - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
            # - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    # Databases
    ## SQL
    sqldata:
        environment:
            #USER: ${MICROSERVICESDOTNET_SQL_USER}
            #PASSWORD: ${MICROSERVICESDOTNET_SQL_PASSWORD}
            SA_PASSWORD: ${MICROSERVICESDOTNET_SQL_SA_PASSWORD}
            ACCEPT_EULA: 'Y'
            MSSQL_PID: Express
        ports:
            - '${MICROSERVICESDOTNET_SQL_PORT}:1433'
        #volumes:
        #    - microservicesdotnet-sqldata:/var/opt/mssql
    ## NoSQL
    nosqldata:
        ports:
            - '${MICROSERVICESDOTNET_NOSQL_PORT}:27017'
        volumes:
            - microservicesdotnet-nosqldata:/data/db

    # Redis
    redisdata:
        ports:
            - '${MICROSERVICESDOTNET_REDIS_PORT}:6379'
        volumes:
            - microservicesdotnet-redisdata:/data

    # Message Broker
    messagebroker:
        ports:
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_MGMT_PLUGIN_PORT}:15672'
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_QUEUE_PORT}:5672'
        expose:
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_MGMT_PLUGIN_PORT}'
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_QUEUE_PORT}'

volumes:
    #microservicesdotnet-sqldata:
    #    external: false
    #    labels:
    #        com.microservicesdotnet.description: 'SQL data volume'
    microservicesdotnet-nosqldata:
        external: false
        labels:
            com.microservicesdotnet.description: 'NoSQL data volume'
    microservicesdotnet-redisdata:
        external: false
        labels:
            com.microservicesdotnet.description: 'Redis data volume'
