version: '3.4'

services:
    # Identity
    identity_sts:
        env_file:
            - Services/Identity/Services.Identity.STS/Development.env
        environment:
            ConnectionStrings__Sql: 'Server=sqldata;Port=${MICROSERVICESDOTNET_SQL_PORT};Database=microservicesdotnet.services.identitydb;User=root;Password=${MICROSERVICESDOTNET_SQL_ROOT_PASSWORD};'
            ExternalEndpoint: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}'
            ClientEndpoints__localization_api: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_LOCALIZATION_API_PORT}'
            ClientEndpoints__web_base_administration: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_WEB_BASE_ADMINISTRATION_PORT}'
        ports:
            - '${MICROSERVICESDOTNET_IDENTITY_STS_PORT}:8080'
        expose:
            - '${MICROSERVICESDOTNET_IDENTITY_STS_PORT}'
        # volumes:
            # - ~/vsdbg:/vsdbg:ro
            # - ./Services:/workspace
            # - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
            # - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    # API
    ## Localization
    localization_api:
        env_file:
            - Services/Localization/Services.Localization.API/Development.env
        environment:
            ConnectionStrings__Sql: 'Server=sqldata;Port=${MICROSERVICESDOTNET_SQL_PORT};Database=microservicesdotnet.services.localizationdb;User=root;Password=${MICROSERVICESDOTNET_SQL_ROOT_PASSWORD};'
            ConnectionStrings__Redis: ${MICROSERVICESDOTNET_REDIS_DB:-redisdata}
            IdentityUrl: 'http://identity_sts:8080'
            IdentityUrlExternal: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}'
        ports:
            - '${MICROSERVICESDOTNET_LOCALIZATION_API_PORT}:8080'
        expose:
            - '${MICROSERVICESDOTNET_LOCALIZATION_API_PORT}'
        # volumes:
            # - ~/vsdbg:/vsdbg:ro
            # - ./Services:/workspace
            # - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
            # - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    # Web
    ## Administration
    #### base-admin
    web_administration_baseadmin:
        env_file:
        - Web/Administration/web-administration/Development.env
        environment:
            AUTHORITYLOGINURL: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}/${MICROSERVICESDOTNET_IDENTITY_STS_LOGIN_PATH}'
            AUTHORITYREDIRECTURL: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_WEB_BASE_ADMINISTRATION_PORT}/'
            AUTHORITYLOGOUTURL: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}/${MICROSERVICESDOTNET_IDENTITY_STS_LOGOUT_PATH}'
            AUTHORITYUSERINFOURL: '${MICROSERVICESDOTNET_EXTERNAL_DNS_NAME_OR_IP}:${MICROSERVICESDOTNET_IDENTITY_STS_PORT}/${MICROSERVICESDOTNET_IDENTITY_STS_USERINFO_PATH}'
        ports:
            - '${MICROSERVICESDOTNET_WEB_BASE_ADMINISTRATION_PORT}:4200'
        expose:
            - '${MICROSERVICESDOTNET_WEB_BASE_ADMINISTRATION_PORT}'
        volumes:
            - ./Web/Administration/web-administration:/workspace
            - /workspace/node_modules

    # Databases
    ## SQL
    sqldata:
        environment:
            MYSQL_USER: ${MICROSERVICESDOTNET_SQL_USER}
            MYSQL_PASSWORD: ${MICROSERVICESDOTNET_SQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MICROSERVICESDOTNET_SQL_ROOT_PASSWORD}
        ports:
            - '${MICROSERVICESDOTNET_SQL_PORT}:3306'
        volumes:
            - microservicesdotnet-sqldata:/var/lib/mysql
    ## NoSQL
    nosqldata:
        ports:
            - '${MICROSERVICESDOTNET_NOSQL_PORT}:27017'
        volumes:
            - microservicesdotnet-nosqldata:/data/db

    # Redis
    redisdata:
        ports:
            - '${MICROSERVICESDOTNET_REDIS_PORT}:6379'
        volumes:
            - microservicesdotnet-redisdata:/data

    # Message Broker
    messagebroker:
        ports:
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_MGMT_PLUGIN_PORT}:15672'
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_QUEUE_PORT}:5672'
        expose:
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_MGMT_PLUGIN_PORT}'
            - '${MICROSERVICESDOTNET_MESSAGEBROKER_QUEUE_PORT}'

volumes:
    microservicesdotnet-sqldata:
        external: false
        labels:
            com.microservicesdotnet.description: 'SQL data volume'
    microservicesdotnet-nosqldata:
        external: false
        labels:
            com.microservicesdotnet.description: 'NoSQL data volume'
    microservicesdotnet-redisdata:
        external: false
        labels:
            com.microservicesdotnet.description: 'Redis data volume'
